variable "cluster_name" {}
variable "eks_version" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "cluster_sg_id" {}
variable "cluster_role_arn" {}
variable "nodegroup_role_arn" {}
variable "on_demand_size" {}
variable "on_demand_type" {}
variable "worker_size" {}
variable "worker_type" {}
